name: absensi_greenliving
description: "A Flutter application for attendance tracking."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  flutter:
      sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  geolocator: ^10.1.0
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  intl: ^0.20.2
  google_fonts: ^6.1.0
  get_storage: ^2.1.1
  excel: ^4.0.0          
  path_provider: ^2.1.2    
  permission_handler: ^11.3.0
  open_file: ^3.3.2
  flutter_launcher_icons: "^0.13.1"      
  flutter_native_splash: "^2.3.1"
  connectivity_plus: ^6.0.0  


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true


  assets:
    - assets/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/Logo.png" 
  min_sdk_android: 21

flutter_native_splash:
  color: "#1B5E20" 
  image: "assets/icon/Logo.png" 
  android_12:
    image: "assets/icon/Logo.png"
    color: "#1B5E20"
  fullscreen: true